version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./nginx.Dockerfile
    volumes:
      - api_static:/DjangoHome/static
      - ui_static:/usr/share/nginx/html
    restart: always
    ports:
      - "80:80"
    depends_on:
      - ui
      - api
      - rabbitmq
  rabbitmq:
    image: lkiran/rabbit-home
    restart: always
    hostname: pi
    ports:
      - "1883:1883"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - rabbit_data:/var/lib/rabbitmq/
      - rabbit_logs:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  api:
    image: lkiran/django-home
#   build:
#     context: .
#   command: gunicorn DjangoHome.wsgi:application --bind 0.0.0.0:8000 --workers 1 --threads 1
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - api_static:/DjangoHome/static
      - api_logs:/DjangoHome/Logs
      - api_db:/DjangoHome/data
    restart: always
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=aa59e3e2-b398-4170-85d8-ef91c2315514
      - ENABLE_FILE_LOGGING=1
      - START_DEVICES=1
      - DEBUG=0
    depends_on:
      - rabbitmq
  ui:
    image: lkiran/ng-home
    ports:
      - "8080:80"
    volumes:
      - ui_static:/usr/share/nginx/html
volumes:
  api_static:
  api_logs:
  api_db:
    driver_opts:
      type: none
      device: /home/pi/DjangoHome/data
      o: bind
  rabbit_data:
  rabbit_logs:
  ui_static:
