version: '3'
services:
    app:
        build: .
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - .:/docker_remote_interpreter