version: '3'
services:
    app:
        build:
            context: .
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        restart: always
        ports:
            - 8000:8000
        volumes:
            - .:/docker_remote_interpreter
        environment:
            - START_DEVICES=1
            - SECRET_KEY=aa59e3e2-b398-4170-85d8-ef91c2315514
            - DEBUG=0