# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.RemoveField(
            model_name='function',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interface',
            name='id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='condition',
            name='Id',
            field=models.CharField(default='o2iCGQZ7KtdTHSQykALqbR', max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='Id',
            field=models.CharField(default='dXhNU3AT6A8DQwxNNoa4TA', max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='function',
            name='Id',
            field=models.CharField(default='cozTUjwUgRrBNdvoCWSd68', max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='Id',
            field=models.CharField(default='aVqD7kSZyHP6ULyuThWzg3', max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='Id',
            field=models.CharField(default='C36ocpGWXnzzPksq2FXVth', max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Id',
            field=models.CharField(default='QJTnavxWGZEhhGQgCXaqfd', max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='Id',
            field=models.CharField(default='VXeL2kSj3W9FNJTxuPwDw9', max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
