# Generated by Django 3.2.25 on 2026-02-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
