# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180731_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 31, 21, 55, 41, 973000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='control',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 31, 21, 55, 50, 525000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 31, 21, 55, 54, 7000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='function',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 31, 21, 56, 2, 127000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interface',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 31, 21, 56, 5, 372000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 31, 21, 56, 8, 836000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 31, 21, 56, 11, 557000)),
            preserve_default=False,
        ),
    ]
