# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180112_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='Id',
            field=models.CharField(default='HxEm5LzbxB', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Property',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Property'),
        ),
        migrations.AlterField(
            model_name='control',
            name='Conditions',
            field=models.ManyToManyField(blank=True, to='app.Condition'),
        ),
        migrations.AlterField(
            model_name='control',
            name='Id',
            field=models.CharField(default='BECbBWrv9Z', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='control',
            name='Tasks',
            field=models.ManyToManyField(blank=True, to='app.Task'),
        ),
        migrations.AlterField(
            model_name='device',
            name='Id',
            field=models.CharField(default='oyYV8CwsBe', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='function',
            name='Id',
            field=models.CharField(default='DKStJYHAYH', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='Id',
            field=models.CharField(default='5uCiEYXNdY', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='Id',
            field=models.CharField(default='kbMWU9GZWX', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='Id',
            field=models.CharField(default='BdVZHZtBmd', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='Property',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Property'),
        ),
    ]
