# Generated by Django 3.2.25 on 2026-02-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_condition_createdon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='Name',
            field=models.CharField(max_length=60),
        ),
    ]
