# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180114_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefab',
            fields=[
                ('Id', models.CharField(default='KmAdW9Fg86', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Template', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='condition',
            name='Id',
            field=models.CharField(default='tSj8VgQawA', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='control',
            name='Id',
            field=models.CharField(default='5C7eLyi4wK', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='Id',
            field=models.CharField(default='Dpat7ctauj', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='function',
            name='Id',
            field=models.CharField(default='HZDjkw8YUk', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='Id',
            field=models.CharField(default='QfT29nfDdW', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='Id',
            field=models.CharField(default='TaTaUXyEtL', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='Id',
            field=models.CharField(default='soyUeEkXWM', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
