# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180731_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefab',
            name='CreatedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 23, 15, 44, 765000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prefab',
            name='ModifiedOn',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 9, 23, 15, 56, 105000)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condition',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='ModifiedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Operator',
            field=models.IntegerField(choices=[(0, b'Equal'), (1, b'NotEqual'), (2, b'Greater'), (3, b'EqualOrGreater'), (4, b'Smaller'), (5, b'EqualOrSmaller')]),
        ),
        migrations.AlterField(
            model_name='control',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='control',
            name='ModifiedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='ModifiedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='function',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='function',
            name='ModifiedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interface',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='interface',
            name='ModifiedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='ModifiedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='CreatedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='ModifiedOn',
            field=models.DateTimeField(),
        ),
    ]
