# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180115_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='AndConditions',
            field=models.ManyToManyField(blank=True, to='app.Condition'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='Id',
            field=models.CharField(default='b7BuXhvmJM', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='control',
            name='Id',
            field=models.CharField(default='7w4tdAbTi2', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='Id',
            field=models.CharField(default='AKembcdAcN', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='function',
            name='Id',
            field=models.CharField(default='T89QcS7ZQP', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='Id',
            field=models.CharField(default='P28KsTMist', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prefab',
            name='Id',
            field=models.CharField(default='XiSvfpWKXR', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='Id',
            field=models.CharField(default='bM4ULdLd7t', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='Id',
            field=models.CharField(default='5UmQv64gxu', editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
