name: Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
        
    - name: Deploy to Docker Host
      uses: wshihadeh/docker-deployment-action@v2
      with:
        remote_docker_host: ${{ secrets.SSH_HOST }}
        remote_docker_port: ${{ secrets.SSH_PORT }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        deploy_path: /home/pi/docker-deployment
        stack_file_name: docker-compose.prod.yaml
        deployment_mode: docker-compose
        args: up -d
        copy_stack_file: true
        pull_images_first: true
