name: Django CI

on:
  push:
    branches: 
    - '*' # any branch
    - '!master' # except master
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # allow manual run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests
      run: |
        python manage.py test
